import Testing
import Foundation
@testable import OQS

// KAT tests MUST run isolated from all other suites. liboqs's NIST-KAT DRBG is
// process-global: `.serialized` only orders tests *within* this suite, so a bare
// `swift test` races keygen in other suites against the seeded stream and fails
// nondeterministically. Run via: swift test --no-parallel --filter KATTests
// (CI runs the bulk suite with --skip KATTests and this suite separately).
//
// The committed digests in Vectors/kat_hashes.json are self-anchored regression
// locks generated by these wrappers under the deterministic seed — they detect
// future drift (e.g. a liboqs update changing output), not present-day
// correctness against external NIST vectors. vendor-liboqs.sh fetches upstream
// KATs into the gitignored UpstreamKATs/ for optional manual cross-checking.
@Suite(.serialized) struct KATTests {
    @Test("ML-KEM-512 KAT digest matches committed hash")
    func mlkem512KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }

        let sk = try MLKEM512.PrivateKey()
        let sealed = try sk.publicKey.generateSharedSecret()
        let blob = sk.publicKey.rawRepresentation + sk.rawRepresentation
            + sealed.ciphertext + sealed.sharedSecret.rawRepresentation
        let digest = KAT.sha3_256Hex(blob)

        let expected = try KATHashes.shared.hash(for: "ML-KEM-512")
        #expect(digest == expected)
    }

    @Test("FrodoKEM-640-AES KAT digest matches committed hash")
    func frodo640aesKAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let sk = try FrodoKEM640AES.PrivateKey()
        let sealed = try sk.publicKey.generateSharedSecret()
        let blob = sk.publicKey.rawRepresentation + sk.rawRepresentation
            + sealed.ciphertext + sealed.sharedSecret.rawRepresentation
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "FrodoKEM-640-AES")))
    }

    @Test("NTRU-HPS-2048-509 KAT digest matches committed hash")
    func ntruhps2048509KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let sk = try NTRUHPS2048509.PrivateKey()
        let sealed = try sk.publicKey.generateSharedSecret()
        let blob = sk.publicKey.rawRepresentation + sk.rawRepresentation
            + sealed.ciphertext + sealed.sharedSecret.rawRepresentation
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "NTRU-HPS-2048-509")))
    }

    @Test("sntrup761 KAT digest matches committed hash")
    func sntrup761KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let sk = try SNTRUP761.PrivateKey()
        let sealed = try sk.publicKey.generateSharedSecret()
        let blob = sk.publicKey.rawRepresentation + sk.rawRepresentation
            + sealed.ciphertext + sealed.sharedSecret.rawRepresentation
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "sntrup761")))
    }

    @Test("ML-DSA-44 KAT digest matches committed hash")
    func mldsa44KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let key = try MLDSA44.PrivateKey()
        let sig = try key.signature(for: Data("KAT".utf8))
        let blob = key.publicKey.rawRepresentation + key.rawRepresentation + sig
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "ML-DSA-44")))
    }

    @Test("MAYO-1 KAT digest matches committed hash")
    func mayo1KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let key = try MAYO1.PrivateKey()
        let sig = try key.signature(for: Data("KAT".utf8))
        let blob = key.publicKey.rawRepresentation + key.rawRepresentation + sig
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "MAYO-1")))
    }

    @Test("SNOVA_24_5_4 KAT digest matches committed hash")
    func snova2454KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let key = try SNOVA24_5_4.PrivateKey()
        let sig = try key.signature(for: Data("KAT".utf8))
        let blob = key.publicKey.rawRepresentation + key.rawRepresentation + sig
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "SNOVA_24_5_4")))
    }

    @Test("OV-Is KAT digest matches committed hash")
    func ovIsKAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let key = try OVIs.PrivateKey()
        let sig = try key.signature(for: Data("KAT".utf8))
        let blob = key.publicKey.rawRepresentation + key.rawRepresentation + sig
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "OV-Is")))
    }

    @Test("BIKE-L1 KAT digest matches committed hash")
    func bikeL1KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let sk = try BIKEL1.PrivateKey()
        let sealed = try sk.publicKey.generateSharedSecret()
        let blob = sk.publicKey.rawRepresentation + sk.rawRepresentation
            + sealed.ciphertext + sealed.sharedSecret.rawRepresentation
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "BIKE-L1")))
    }

    @Test("XMSS-SHA2_10_256 KAT digest matches committed hash")
    func xmssSha2H10KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let key = try XMSS.PrivateKey(.sha2_10_256)
        var serialized: Data? = nil
        let sig = try key.signature(for: Data("KAT".utf8)) { serialized = $0 }
        let blob = key.publicKey.rawRepresentation + (serialized ?? Data()) + sig
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "XMSS-SHA2_10_256")))
    }

    @Test("LMS_SHA256_H5_W1 KAT digest matches committed hash")
    func lmsH5W1KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let key = try LMS.PrivateKey(.sha256_h5_w1)
        var serialized: Data? = nil
        let sig = try key.signature(for: Data("KAT".utf8)) { serialized = $0 }
        let blob = key.publicKey.rawRepresentation + (serialized ?? Data()) + sig
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "LMS_SHA256_H5_W1")))
    }

    // eFrodoKEM is the pre-0.16.0 FrodoKEM algorithm renamed; its digest must
    // equal the FrodoKEM-640-AES anchor committed before the 0.16.0 bump —
    // that identity is the cross-version check that the C output is unchanged.
    @Test("eFrodoKEM-640-AES KAT digest matches committed hash")
    func efrodo640aesKAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let sk = try EFrodoKEM640AES.PrivateKey()
        let sealed = try sk.publicKey.generateSharedSecret()
        let blob = sk.publicKey.rawRepresentation + sk.rawRepresentation
            + sealed.ciphertext + sealed.sharedSecret.rawRepresentation
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "eFrodoKEM-640-AES")))
    }

    @Test("HQC-1 KAT digest matches committed hash")
    func hqc1KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let sk = try HQC1.PrivateKey()
        let sealed = try sk.publicKey.generateSharedSecret()
        let blob = sk.publicKey.rawRepresentation + sk.rawRepresentation
            + sealed.ciphertext + sealed.sharedSecret.rawRepresentation
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "HQC-1")))
    }

    @Test("mqom2_cat1_gf16_fast_r3 KAT digest matches committed hash")
    func mqom2Cat1FastR3KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let blob: Data = try onLargeStack {
            let key = try MQOM2Cat1GF16FastR3.PrivateKey()
            let sig = try key.signature(for: Data("KAT".utf8))
            return key.publicKey.rawRepresentation + key.rawRepresentation + sig
        }
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "mqom2_cat1_gf16_fast_r3")))
    }
}
