/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define APPLY_NAMESPACE oqs_sig_private_mqom2_cat5_gf16_fast_r5_default_
#define APPLY_PUBLIC_API_NAMESPACE oqs_sig_pubapi_mqom2_cat5_gf16_fast_r5_default_
#define MQOM2_FOR_LIBOQS
#define MQOM2_PARAM_BASE_FIELD 4
#define MQOM2_PARAM_NBROUNDS 5
#define MQOM2_PARAM_SECURITY 256
#define MQOM2_PARAM_TRADEOFF 0
#define NO_EMBEDDED_SRAM_SECTION
#define PIOP_BITSLICE
#define USE_ENC_X8
#define USE_PIOP_CACHE
#define USE_PRG_CACHE
#define USE_XOF_X4
#include "sig_mqom_mqom2_cat5_gf16_fast_r5.c"
#include "mqom_mqom_common/blc_default.c"
#include "mqom_mqom_common/blc_memopt_x1.c"
#include "mqom_mqom_common/blc_memopt_x2.c"
#include "mqom_mqom_common/blc_memopt_x4.c"
#include "mqom_mqom_common/blc_memopt.c"
#include "mqom_mqom_common/crypto_sign.c"
#include "mqom_mqom_common/expand_mq.c"
#include "mqom_mqom_common/ggm_tree.c"
#include "mqom_mqom_common/keygen.c"
#include "mqom_mqom_common/piop_bitslice.c"
#include "mqom_mqom_common/piop_default.c"
#define ExpandBatchingChallenge mqom_piop_memopt_ExpandBatchingChallenge
#include "mqom_mqom_common/piop_memopt.c"
#undef ExpandBatchingChallenge
#include "mqom_mqom_common/prg.c"
#include "mqom_mqom_common/rijndael_aes_ni.c"
#define sbox mqom_rijndael_ct64_sbox
#define rcon mqom_rijndael_ct64_rcon
#include "mqom_mqom_common/rijndael_ct64.c"
#undef sbox
#undef rcon
#include "mqom_mqom_common/rijndael_external.c"
#define sbox mqom_rijndael_ref_sbox
#define rcon mqom_rijndael_ref_rcon
#include "mqom_mqom_common/rijndael_ref.c"
#undef sbox
#undef rcon
#include "mqom_mqom_common/rijndael_table.c"
#include "mqom_mqom_common/sign_memopt.c"
#include "mqom_mqom_common/sign.c"
#include "mqom_mqom_common/xof.c"
