/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define HQC_ARCH_REF 1
#define PQCHQC_NAMESPACE_PREFIX PQCHQC_HQC5_C_
#define USE_OQS_RANDOMBYTES
#include "pqc-hqc_hqc-5_ref/code.c"
#include "pqc-hqc_hqc-5_ref/crypto_memset.c"
#include "pqc-hqc_hqc-5_ref/fft.c"
#include "pqc-hqc_hqc-5_ref/gf.c"
#include "pqc-hqc_hqc-5_ref/gf2x.c"
#include "pqc-hqc_hqc-5_ref/hqc.c"
#include "pqc-hqc_hqc-5_ref/kem.c"
#include "pqc-hqc_hqc-5_ref/parsing.c"
#include "pqc-hqc_hqc-5_ref/reed_muller.c"
#include "pqc-hqc_hqc-5_ref/reed_solomon.c"
#include "pqc-hqc_hqc-5_ref/symmetric.c"
#include "pqc-hqc_hqc-5_ref/vector.c"
